-- AlterTable
ALTER TABLE `Hostpitals` ALTER COLUMN `hospitalCode` DROP DEFAULT,
    ALTER COLUMN `licenseNumber` DROP DEFAULT,
    ALTER COLUMN `HNCode` DROP DEFAULT,
    ALTER COLUMN `address` DROP DEFAULT,
    ALTER COLUMN `amphur` DROP DEFAULT,
    ALTER COLUMN `amphurId` DROP DEFAULT,
    ALTER COLUMN `email` DROP DEFAULT,
    ALTER COLUMN `image` DROP DEFAULT,
    ALTER COLUMN `isActive` DROP DEFAULT,
    ALTER COLUMN `phone` DROP DEFAULT,
    ALTER COLUMN `province` DROP DEFAULT,
    ALTER COLUMN `provinceId` DROP DEFAULT,
    ALTER COLUMN `referCode` DROP DEFAULT,
    ALTER COLUMN `serviceDesc` DROP DEFAULT,
    ALTER COLUMN `tambon` DROP DEFAULT,
    ALTER COLUMN `tanbonId` DROP DEFAULT,
    ALTER COLUMN `zipCode` DROP DEFAULT;

-- AlterTable
ALTER TABLE `ReferList` ALTER COLUMN `department` DROP DEFAULT,
    ALTER COLUMN `departmentId` DROP DEFAULT,
    ALTER COLUMN `originHospital` DROP DEFAULT,
    ALTER COLUMN `referDate` DROP DEFAULT,
    ALTER COLUMN `confirmDate` DROP DEFAULT,
    ALTER COLUMN `destinationHospital` DROP DEFAULT;

-- AlterTable
ALTER TABLE `User` ALTER COLUMN `isActive` DROP DEFAULT;
