-- CreateTable
CREATE TABLE `opds` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `opd_code` VARCHAR(191) NULL,
    `customer_id` INTEGER NULL,
    `hn` VARCHAR(191) NULL,
    `opd_bmi` VARCHAR(191) NULL,
    `opd_IOPatLE` VARCHAR(191) NULL,
    `opd_IOPatRE` VARCHAR(191) NULL,
    `opd_VAccLE` VARCHAR(191) NULL,
    `opd_VAccRE` VARCHAR(191) NULL,
    `opd_VAscLE` VARCHAR(191) NULL,
    `opd_VAscRE` VARCHAR(191) NULL,
    `opd_alcohol` INTEGER NULL,
    `opd_fag` INTEGER NULL,
    `opd_breathing` VARCHAR(191) NULL,
    `opd_bsa` VARCHAR(191) NULL,
    `opd_cc` VARCHAR(191) NULL,
    `opd_diagnosisList` VARCHAR(191) NULL,
    `opd_diastolic` VARCHAR(191) NULL,
    `opd_docName` VARCHAR(191) NULL,
    `opd_docNote` VARCHAR(191) NULL,
    `opd_dx` VARCHAR(191) NULL,
    `opd_file` VARCHAR(191) NULL,
    `opd_ga` VARCHAR(191) NULL,
    `opd_height` INTEGER NULL,
    `opd_weight` INTEGER NULL,
    `opd_hpi` VARCHAR(191) NULL,
    `opd_o2sat` VARCHAR(191) NULL,
    `opd_pe` VARCHAR(191) NULL,
    `opd_pmh` VARCHAR(191) NULL,
    `opd_pressure` VARCHAR(191) NULL,
    `opd_pulse` VARCHAR(191) NULL,
    `opd_systonic` VARCHAR(191) NULL,
    `opd_temperature` VARCHAR(191) NULL,
    `opd_vas` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
